from pallas.product.arknights_kb.startup import register_arknights_kb_startup_hook
from pallas.product.llm.group_insight_processor import register_group_insight_startup_hook
from pallas.product.llm.repeater_semantic_style import register_semantic_style_cache_startup_hook
from pallas.product.llm.runtime_api import register_llm_tools_startup_hook

register_llm_tools_startup_hook()
register_semantic_style_cache_startup_hook()
register_group_insight_startup_hook()
register_arknights_kb_startup_hook()
