"""WebUI 配置项展示用中文名。"""

from __future__ import annotations

# 键为 Pydantic 字段名；插件与通用配置共用。
FIELD_LABELS: dict[str, str] = {
    "ai_server_host": "AI 服务主机",
    "ai_server_port": "AI 服务端口",
    "answer_threshold": "接话随机阈值",
    "answer_threshold_weights": "接话阈值权重",
    "api_key": "备线访问密钥",
    "auto_enroll": "自动获取社区访问口令",
    "base_url": "备线服务地址",
    "bootstrap_url": "多机协同中心地址",
    "bot_status_list_mode": "在吗名册模式",
    "bot_status_notice_email": "告警收件邮箱",
    "bot_status_offline_grace_time": "离线宽限（秒）",
    "bots": "已连接牛牛 QQ 集合",
    "chat_enable": "启用酒后 RWKV（独立通道）",
    "chat_endpoint": "聊天接口路径",
    "chat_tts_enable": "酒后对话附带语音",
    "claim_ttl_sec": "去重保留秒数",
    "command_limit_overrides": "命令冷却覆盖",
    "command_permission_overrides": "命令权限覆盖",
    "command_start": "命令前缀",
    "community_api_base": "共享语料服务地址",
    "community_contribute": "把新学到的回复上传到社区",
    "corpus_backfill_batch_size": "每轮同步条数",
    "corpus_backfill_enabled": "把历史语料同步到社区",
    "corpus_backfill_interval_sec": "同步间隔（秒）",
    "corpus_backfill_max_per_minute": "同步限速（次/分钟）",
    "community_enabled": "使用社区共享接话库",
    "community_stats_enabled": "上报在线统计",
    "community_stats_endpoint": "统计上报地址",
    "community_stats_interval_sec": "上报间隔",
    "community_stats_token": "统计上报口令",
    "community_token": "共享语料访问口令",
    "coord_redis_url": "多进程共用去重服务地址",
    "cross_group_threshold": "跨群提升语料阈值",
    "custom_styles": "自定义样式列表",
    "default_style": "默认帮助样式",
    "default_styles": "内置样式列表",
    "del_session_endpoint": "清除会话路径",
    "dream_archive_image_probability": "带图概率",
    "dream_drift_queue_tick_probability": "漂流队列推进概率",
    "dream_echo_resample_attempts": "回声重采样次数",
    "dream_hist_resample_attempts": "历史梦重采样次数",
    "dream_history_recency_power": "历史梦新近权重",
    "dream_history_recent_dedupe_max": "近期梦去重条数",
    "dream_message_retention_days": "梦消息保留天数",
    "dream_prefer_learned_echo_probability": "优先已学回声概率",
    "dream_worker_sleep_max_sec": "做梦线程最长休眠（秒）",
    "dream_worker_sleep_min_sec": "做梦线程最短休眠（秒）",
    "drunk_tts_min_chars": "酒后附带语音最短字数",
    "drunk_tts_min_drunkenness": "酒后附带语音最低醉酒度",
    "duel_auto_sync_operators": "启动同步干员表",
    "duel_avatar_download_on_startup": "启动批量下载头像",
    "duel_avatar_download_on_use": "用时下载头像",
    "duel_bot_cooldown_sec": "决斗冷却（秒）",
    "duel_bot_qte_fail_silent_chance": "QTE 失败沉默概率",
    "duel_bot_qte_fail_speak_wrong_chance": "QTE 失败乱说话概率",
    "duel_bot_qte_intrusion_success_rate": "牛 QTE 乱入成功率",
    "duel_bot_qte_keyword_success_rate": "牛 QTE 命令成功率",
    "duel_compact_round": "紧凑回合发群",
    "duel_exchange_qte_chance": "QTE 额外触发概率",
    "duel_exchange_qte_race_chance": "QTE 抢答概率",
    "duel_intrusion_pallas_roll_chance": "帕拉斯乱入概率",
    "duel_intrusion_race_chance": "乱入抢答概率",
    "duel_operator_intrusion_chance": "干员乱入概率",
    "duel_penalty_bot_fake_msg": "牛牛败北台词",
    "duel_penalty_bot_sad_msg": "牛牛败北沉默台词",
    "duel_penalty_human_noise_msg": "人败北台词",
    "duel_penalty_loser_card": "败者群名片",
    "duel_penalty_minutes": "败者禁言时长（分钟）",
    "duel_penalty_winner_card": "胜者群名片",
    "duel_player_rounds_max": "玩家回合上限",
    "duel_public_round_weight": "公开回合权重",
    "duel_public_terra_weight_mult": "公开地形权重倍率",
    "duel_qte_event_weight_mult": "QTE 事件权重倍率",
    "duel_round_pause_max_sec": "回合间最长暂停（秒）",
    "duel_round_pause_min_sec": "回合间最短暂停（秒）",
    "duel_total_rounds": "默认总回合数",
    "duplicate_reply": "回复去重轮数",
    "enable_auto_reply_on_reaction": "跟他人表情回应",
    "enable_custom_style_loading": "加载自定义样式",
    "enable_face_reaction": "QQ表情自动回应",
    "enable_kick_ban": "被踢出群时加入黑名单",
    "enable_probability_reaction": "随机表情回应",
    "enable_reaction": "启用表情回应",
    "enabled": "启用多机协同",
    "fanout_enabled": "多只牛牛同群时一起接话",
    "fanout_max_bots": "同群接话时最多参与几只牛",
    "group_style_enabled": "启用群风格自动生长",
    "fed_contribute": "把本群新回复分享给社区",
    "fed_enabled": "使用社区共享接话库",
    "federate_id": "本站在社区中的编号",
    "deployment_name": "部署显示名",
    "federate_ingress_enabled": "多机部署时过滤重复群消息",
    "prefer_local_owner": "命令群归属优先本机",
    "federate_redis_prefix": "去重键前缀",
    "find_cache_max": "查询缓存条数上限",
    "find_cache_ttl_sec": "查询缓存保留秒数",
    "greeting_fanout_texts": "全员同响命令列表",
    "dispatch_lanes_enabled": "限制同时处理的消息数量",
    "lane_acquire_timeout_sec": "排队等待超时（秒）",
    "lane_busy_reply": "太忙时的自动回复",
    "lane_chat": "LLM 对话类同时处理上限",
    "lane_chat_adaptive_max": "积压时 LLM 对话类最高并发",
    "lane_command": "命令类同时处理上限",
    "lane_remote": "访问外网服务同时处理上限",
    "lane_storage": "读写数据库同时处理上限",
    "lane_wait_overload_ms": "排队过久判定阈值（毫秒）",
    "matcher_dispatch_enabled": "先筛掉与牛牛无关的消息",
    "matcher_dispatch_overload_threshold": "预筛过载阈值",
    "chat_drop_on_overload": "过载时整段丢弃闲聊",
    "conversation_scheduler_enabled": "启用群消息公平调度",
    "conversation_scheduler_concurrency": "同时处理群数",
    "conversation_scheduler_adaptive_max": "积压时最多同时处理群数",
    "conversation_scheduler_adaptive_interval_sec": "调度扩容检查间隔（秒）",
    "conversation_scheduler_max_pending": "总待处理消息上限",
    "conversation_scheduler_per_key_pending": "单群待处理消息上限",
    "route_index_enabled": "命令快速定位（推荐开启）",
    "route_index_strict": "只响应已登记的命令",
    "send_queue_enabled": "发送消息排队（防刷屏）",
    "send_queue_enqueue_timeout_sec": "排队发送超时（秒）",
    "send_queue_max_depth": "待发消息队列长度",
    "send_queue_min_interval_ms": "同一只牛最短发送间隔（毫秒）",
    "send_queue_workers": "发送消息的工作线程数",
    "ignored_plugins": "隐藏插件列表",
    "help_tag_overrides": "帮助图分组覆盖",
    "inbound_filter_api_fail_open": "审查失败时放行",
    "inbound_filter_api_key": "审查接口密钥",
    "inbound_filter_api_timeout_sec": "审查超时（秒）",
    "inbound_filter_api_url": "审查接口（备用）",
    "inbound_filter_substrings": "关键词拦截",
    "ingress_bypass_unified": "单进程运行时跳过消息预筛",
    "instance_secret": "加入协同的密钥",
    "learn_concurrency": "后台学习并发数",
    "learn_queue_max_size": "学习队列容量",
    "maa_attach_screenshot": "指令后自动截图",
    "maa_combat_auto_prepare": "作战前自动准备",
    "maa_get_task_endpoint": "取任务完整地址",
    "maa_get_task_path": "取任务路径",
    "maa_public_base_url": "对外访问地址",
    "maa_report_status_endpoint": "报状态完整地址",
    "maa_report_status_path": "报状态路径",
    "maa_seen_ttl_seconds": "未绑定设备保留（秒）",
    "merge_order": "接话查找顺序",
    "merge_strategy": "重复句如何合并",
    "model": "备线模型名",
    "name": "备线显示名",
    "llm_chat_enable": "启用 LLM 对话（已弃用，请用 LLM_CHAT_ENABLED）",
    "llm_chat_enabled": "启用智能对话",
    "log_level": "日志级别",
    "llm_governance_enabled": "限制 LLM 对话频率与字数",
    "llm_chat_max_concurrency": "LLM 对话并发上限",
    "llm_chat_queue_enabled": "高峰对话排队等待",
    "llm_chat_queue_max": "排队对话上限",
    "llm_chat_queue_wait_sec": "排队等待超时（秒）",
    "llm_repeater_feedback_enabled": "收集 LLM 对话反哺",
    "llm_repeater_bias_enabled": "反哺参与接话打分",
    "conversation_feature_level": "对话能力档位",
    "llm_reply_gate_enabled": "过滤无意义 @",
    "llm_shut_up_silence_enabled": "闭嘴静默",
    "llm_shut_up_silence_min_sec": "闭嘴静默最短（秒）",
    "llm_shut_up_silence_max_sec": "闭嘴静默最长（秒）",
    "llm_chat_queue_merge": "冷却期合并多条 @",
    "llm_output_filter_enabled": "回复输出过滤",
    "llm_output_filter_chat_hard_phrases": "LLM 对话硬拦截词",
    "llm_output_filter_chat_soft_phrases": "LLM 对话软拦截词",
    "llm_memory_rag_enabled": "群记忆检索",
    "llm_vector_retrieve": "记忆/知识检索模式",
    "llm_embedding_model": "Embedding 模型",
    "llm_embedding_provider": "向量提供方",
    "llm_embedding_provider_id": "Embedding 线路",
    "llm_embedding_base_url": "Embedding 接口地址",
    "llm_embedding_api_key": "Embedding API Key",
    "llm_embedding_api_backends": "Embedding 备线",
    "llm_memory_rag_top_k": "记忆检索条数",
    "llm_memory_max_per_group": "每群记忆上限",
    "llm_memory_content_max_len": "单条记忆字数上限",
    "llm_memory_auto_episode_enabled": "自动沉淀会话为记忆",
    "llm_memory_auto_episode_summary_enabled": "自动摘要群内共同事件",
    "llm_memory_auto_episode_cooldown_sec": "自动沉淀冷却（秒）",
    "llm_memory_auto_person_facts_enabled": "自动总结群友个人偏好",
    "llm_memory_auto_person_facts_cooldown_sec": "个人偏好总结冷却（秒）",
    "llm_memory_auto_person_facts_daily_budget": "个人偏好总结每日上限",
    "llm_memory_graph_extract_enabled": "记忆图谱抽取",
    "llm_memory_graph_extract_on_write": "写入后自动抽取图谱",
    "llm_memory_hiergraph_max_layers": "分层图谱最大层数",
    "llm_memory_decay_half_life_days": "记忆淡出半衰期（天）",
    "llm_memory_decay_min_importance": "记忆淡出重要性下限",
    "llm_memory_hit_boost_enabled": "记忆命中加权",
    "llm_memory_hit_boost_sec": "记忆命中加权有效期（秒）",
    "llm_knowledge_file_ingest_enabled": "文件知识自动摄入",
    "llm_relationship_notes_enabled": "关系备注",
    "llm_relationship_affinity_enabled": "好感度记录",
    "llm_relationship_affinity_ambient_enabled": "普通群聊好感度观察",
    "llm_relationship_affinity_delta_max": "单次好感度变动上限",
    "llm_relationship_affinity_llm_cooldown_s": "好感度大模型判定冷却（秒）",
    "llm_relationship_affinity_llm_daily_limit": "好感度大模型判定每日上限",
    "llm_relationship_affinity_daily_decay_step": "好感度每日回落幅度",
    "llm_relationship_affinity_silence_threshold": "好感度静默阈值",
    "llm_relationship_affinity_silence_max_penalty": "好感度静默最大扣分",
    "arknights_kb_enabled": "启用方舟干员查询",
    "arknights_kb_auto_sync": "缺数据时自动同步",
    "llm_session_enabled": "记住多轮上下文",
    "llm_session_user_window": "用户上下文条数",
    "llm_session_user_storage_window": "用户历史存储条数",
    "llm_session_group_window": "群旁听上下文条数",
    "llm_session_group_ambient_enabled": "注入群旁听上下文",
    "llm_session_user_ttl_sec": "用户会话过期（秒）",
    "llm_session_private_ttl_sec": "私聊会话过期（秒）",
    "llm_session_max_content_len": "单条会话字数上限",
    "llm_session_strip_vision_enabled": "写入会话时去掉图片",
    "llm_session_summary_enabled": "会话过长时生成摘要",
    "llm_session_summary_threshold": "触发摘要的消息条数",
    "llm_session_summary_keep_messages": "摘要后保留近期条数",
    "llm_session_summary_cooldown_sec": "会话摘要冷却（秒）",
    "llm_speak_perception_enabled": "启用发言感知",
    "llm_speak_mention_enabled": "别名提及时进对话",
    "llm_speak_ambient_enabled": "氛围插嘴",
    "llm_speak_ambient_rate": "氛围插嘴概率",
    "llm_speak_ambient_min_score": "氛围插嘴最低分",
    "llm_speak_ambient_cooldown_sec": "氛围插嘴冷却（秒）",
    "llm_speak_ambient_budget_limit": "氛围插嘴预算次数",
    "llm_speak_ambient_budget_window_sec": "氛围插嘴预算窗口（秒）",
    "llm_speak_min_alias_len": "别名最短匹配长度",
    "llm_speak_followup_enabled": "硬触发后续聊软窗",
    "llm_speak_followup_window_sec": "续聊软窗时长（秒）",
    "llm_speak_followup_max_total_sec": "续聊最长总时长（秒）",
    "llm_chat_char_budget": "LLM 对话上下文字符预算",
    "llm_tools_enabled": "允许调用工具",
    "llm_tools_selective": "按意图筛选工具",
    "llm_tools_soft_recall_enabled": "软召回工具候选",
    "llm_tools_soft_recall_min_score": "软召回最低匹配分",
    "llm_tools_soft_recall_max_candidates": "软召回最多候选数",
    "llm_tools_max_rounds": "工具调用最多轮数",
    "llm_tools_blacklist": "工具黑名单",
    "llm_tools_desc_max_len": "工具描述最大长度",
    "mcp_servers": "MCP 服务器",
    "llm_mcp_http_allowlist": "MCP HTTP 允许前缀",
    "web_search_api_url": "搜索接口完整地址",
    "tavily_api_key": "搜索接口密钥",
    "llm_reply_postprocess_enabled": "回复后处理",
    "llm_reply_typo_enabled": "偶发近音错别字",
    "llm_reply_typo_rate": "单字错别字概率",
    "llm_reply_split_randomize_enabled": "短回复随机整句发出",
    "llm_reply_split_randomize_keep_rate": "整句发出的概率",
    "llm_bubble_delay_base_sec": "气泡间隔基础值（秒）",
    "llm_bubble_delay_per_char": "气泡间隔每字增量（秒）",
    "llm_bubble_delay_jitter": "气泡间隔抖动（±比例）",
    "llm_sticker_fit_enabled": "表情适配与反馈",
    "llm_chat_sticker_enabled": "Bot 表情图",
    "llm_chat_sticker_cooldown_sec": "表情图冷却（秒）",
    "llm_sticker_vision_enabled": "视觉模型选表情图 / 聊天看图",
    "llm_sticker_vision_candidate_count": "视觉选图候选数",
    "llm_sticker_vision_timeout_sec": "视觉选图超时（秒）",
    "llm_sticker_vision_max_per_hour": "视觉选图每小时上限",
    "llm_sticker_label_realtime_daily_limit": "标签实时标注每日预算",
    "llm_semantic_style_realtime_daily_limit": "语义风格标注每日预算",
    "llm_sticker_habit_enabled": "表情包习惯沉淀",
    "llm_sticker_habit_min_count": "表情包习惯最少发送次数",
    "llm_sticker_habit_backfill_days": "表情包习惯回填天数",
    "llm_reply_effect_eval_enabled": "记录回复效果评分",
    "llm_chat_system_prompt_path": "系统提示词文件",
    "llm_chat_min_priority": "LLM 对话指令优先级",
    "llm_chat_endpoint": "LLM 对话接口路径",
    "llm_del_session_endpoint": "清除会话路径",
    "ollama_chat_endpoint": "LLM 对话接口路径（已弃用）",
    "ollama_del_session_endpoint": "清除会话路径（已弃用）",
    "ollama_enable": "启用 LLM 对话（已弃用键名）",
    "ollama_min_priority": "LLM 对话指令优先级（已弃用）",
    "ollama_system_prompt_path": "系统提示词文件（已弃用）",
    "omit_response_format": "备线省略返回格式",
    "cost_per_image": "单张费用",
    "on_remote_failure": "远端失败策略",
    "pallas_auto_update_notify_bot_id": "自动更新汇报用牛 QQ",
    "pallas_auto_update_notify_superusers": "自动更新成功后私聊超管",
    "pallas_image_api_backends": "备用网关",
    "pallas_image_api_key": "主网关密钥",
    "pallas_image_aspect_ratio": "画幅比例",
    "pallas_image_base_url": "主服务地址",
    "pallas_image_cost_per_image": "主网关单张费用",
    "pallas_image_stats_cost_currency": "画画费用币种",
    "pallas_image_default_edit_prompt": "编辑默认提示词",
    "pallas_image_draw_command_cooldown": "群冷却（秒）",
    "pallas_image_draw_group_whitelist": "群白名单",
    "pallas_image_draw_max_pending": "排队上限",
    "pallas_image_draw_unlimited": "不限制每日次数",
    "pallas_image_draw_per_user_limit": "每日免费次数",
    "pallas_image_draw_total_timeout": "总超时（秒）",
    "pallas_image_backend_attempt_timeout": "备用网关超时（秒）",
    "pallas_image_draw_unlimited_group_ids": "无限次数群",
    "pallas_image_draw_unlimited_user_ids": "无限次数用户",
    "pallas_image_http_transport": "HTTP 客户端",
    "pallas_image_http_user_agent": "User-Agent",
    "pallas_image_max_concurrency": "全局并发上限",
    "pallas_image_max_param_attempts": "参数尝试上限",
    "pallas_image_merge_reference_urls_into_prompt": "参考图写进提示词",
    "pallas_image_min_priority": "指令优先级",
    "pallas_image_model": "默认模型",
    "pallas_image_primary_name": "主网关名称",
    "pallas_image_provider_id": "沿用 Provider",
    "meme_ai_enabled": "启用 AI 推荐",
    "meme_ai_provider_id": "沿用 Provider",
    "meme_ai_model": "推荐模型",
    "meme_ai_top_k": "候选 Top-K",
    "meme_ai_timeout": "AI 超时（秒）",
    "pallas_image_quality": "生成质量",
    "pallas_image_ref_download_timeout": "参考图超时（秒）",
    "pallas_image_request_timeout": "请求超时（秒）",
    "pallas_image_response_format": "返回格式",
    "pallas_image_size": "像素尺寸",
    "pallas_image_slow_param_fallback": "失败试慢档",
    "pallas_image_tls_impersonate": "TLS 指纹",
    "pallas_image_use_edits_for_reference_images": "参考图走编辑",
    "pallas_protocol_auto_download_runtime": "缺少时自动下载",
    "pallas_protocol_bind_host": "本地监听地址",
    "pallas_protocol_default_args": "启动命令参数",
    "pallas_protocol_default_command": "NapCat 启动命令",
    "pallas_protocol_default_working_dir": "子进程工作目录",
    "pallas_protocol_docker_gid": "容器运行 GID",
    "pallas_protocol_docker_image": "NapCat Docker 镜像",
    "pallas_protocol_docker_internal_webui_port": "容器内网页端口",
    "pallas_protocol_docker_memory_limit": "容器内存上限",
    "pallas_protocol_docker_memory_swap": "容器 swap 上限",
    "pallas_protocol_docker_network_mode": "Docker 网络模式",
    "pallas_protocol_docker_onebot_host": "容器访问宿主机地址",
    "pallas_protocol_docker_shm_size": "容器共享内存大小",
    "pallas_protocol_docker_uid": "容器运行 UID",
    "pallas_protocol_enabled": "启用协议端管理",
    "pallas_protocol_follow_bot_lifecycle": "随牛牛启停实例",
    "pallas_protocol_restart_max_concurrency": "批量重启最大并发",
    "pallas_protocol_restart_stagger_s": "批量 rolling 间隔秒数",
    "pallas_protocol_github_repo": "NapCat 下载仓库",
    "pallas_protocol_github_token": "GitHub 下载令牌",
    "pallas_protocol_instances_root": "实例数据总目录",
    "pallas_protocol_linux_appimage_args": "AppImage 启动参数",
    "pallas_protocol_linux_use_docker": "Linux 用 Docker 跑 NapCat",
    "pallas_protocol_linux_use_xvfb": "Linux 用虚拟显示器",
    "pallas_protocol_linux_xvfb_args": "虚拟显示器参数",
    "pallas_protocol_linux_xvfb_command": "虚拟显示器命令",
    "pallas_protocol_max_log_lines": "协议日志行数上限",
    "pallas_protocol_onebot_client_name": "连接牛牛名称",
    "pallas_protocol_onebot_ws_host": "牛牛 WS 主机",
    "pallas_protocol_onebot_ws_path": "牛牛 WS 路径",
    "pallas_protocol_onebot_ws_port": "牛牛 WS 端口",
    "pallas_protocol_onebot_ws_url": "牛牛完整 WS 地址",
    "pallas_protocol_program_dir": "NapCat 程序目录",
    "pallas_protocol_release_asset": "NapCat 发布包名",
    "pallas_protocol_release_tag": "NapCat 版本标签",
    "pallas_protocol_shell_template_dir": "启动脚本模板目录",
    "pallas_protocol_snowluma_docker_auto_aux_bind_hi": "辅助端口上限",
    "pallas_protocol_snowluma_docker_auto_aux_bind_lo": "辅助端口下限",
    "pallas_protocol_snowluma_docker_auto_bind_port_hi": "自动绑定端口上限",
    "pallas_protocol_snowluma_docker_auto_bind_port_lo": "自动绑定端口下限",
    "pallas_protocol_snowluma_docker_host_novnc_port": "宿主机 noVNC 端口",
    "pallas_protocol_snowluma_docker_host_vnc_port": "宿主机 VNC 端口",
    "pallas_protocol_snowluma_docker_image": "SnowLuma Docker 镜像",
    "pallas_protocol_snowluma_docker_internal_novnc_port": "容器 noVNC 端口",
    "pallas_protocol_snowluma_docker_internal_onebot_http_port": "SnowLuma HTTP 端口",
    "pallas_protocol_snowluma_docker_internal_onebot_ws_port": "SnowLuma WS 端口",
    "pallas_protocol_snowluma_docker_internal_vnc_port": "容器 VNC 端口",
    "pallas_protocol_snowluma_docker_internal_webui_port": "SnowLuma 容器网页端口",
    "pallas_protocol_snowluma_docker_shm_size": "SnowLuma 共享内存",
    "pallas_protocol_snowluma_docker_memory_limit": "SnowLuma 内存上限",
    "pallas_protocol_snowluma_docker_memory_swap": "SnowLuma 内存+Swap",
    "pallas_protocol_snowluma_docker_vnc_passwd": "VNC 登录密码",
    "pallas_protocol_snowluma_github_repo": "SnowLuma 下载仓库",
    "pallas_protocol_snowluma_linux_use_docker": "Linux 用 Docker 跑 SnowLuma",
    "pallas_protocol_snowluma_program_dir": "SnowLuma 程序目录",
    "pallas_protocol_snowluma_release_asset": "SnowLuma 发布包名",
    "pallas_protocol_snowluma_release_tag": "SnowLuma 版本标签",
    "pallas_protocol_web_implementation": "协议网页实现",
    "pallas_protocol_webui_enabled": "启用协议端网页",
    "pallas_protocol_webui_path": "自定义网页挂载路径",
    "pallas_protocol_webui_port_max": "网页端口上限",
    "pallas_protocol_webui_port_min": "网页端口下限",
    "pallas_webui_allowed_origins": "允许的来源列表",
    "pallas_webui_cors": "允许跨域访问",
    "pallas_webui_dev_mode": "开发模式（跳过登录）",
    "pallas_webui_dist_zip_asset": "前端压缩包文件名",
    "pallas_webui_dist_zip_repo": "前端 GitHub 仓库",
    "pallas_webui_dist_zip_tag": "前端发布版本",
    "pallas_webui_dist_zip_url": "前端包直链",
    "pallas_webui_enabled": "启用网页控制台",
    "pallas_webui_http_base": "控制台路径前缀",
    "pallas_webui_log_lines_max": "运行日志行数上限",
    "path": "样式目录路径",
    "play_endpoint": "播放接口路径",
    "poke_limit_max": "时段内戳一戳回应上限",
    "poke_limit_window": "戳一戳限流窗口（秒）",
    "reaction_probability": "表情回应概率",
    "remote_find_enabled": "本机没有时查社区",
    "repeat_ignore_user_ids": "复读忽略 QQ 列表",
    "repeat_threshold": "复读触发次数",
    "reply_answers_cap": "接话候选条数上限",
    "reply_messages_cap": "接话历史条数上限",
    "reply_query_timeout_sec": "接话查询超时（秒）",
    "reply_snapshot_max": "接话快照条数上限",
    "reply_snapshot_ttl_sec": "接话快照保留秒数",
    "reply_with_same_emoji": "跟回应用相同表情",
    "request_endpoint": "唱歌请求路径",
    "request_handler_notify_superusers": "额外通知超管",
    "request_handler_poll_doubt_friends": "轮询可疑好友",
    "save_count_threshold": "持久化消息条数",
    "save_reserved_size": "持久化后保留条数",
    "save_time_threshold": "持久化时间间隔（秒）",
    "scrub_api_url": "自建审查接口",
    "scrub_baidu_api_key": "百度 API Key",
    "scrub_baidu_block_suspected": "疑似违规也拦截",
    "scrub_baidu_censor_url": "百度接口地址",
    "scrub_baidu_secret_key": "百度 Secret Key",
    "scrub_baidu_strategy_id": "百度策略编号",
    "scrub_lexicon_extra": "追加敏感词",
    "scrub_lexicon_path": "词表文件路径",
    "scrub_review_providers": "在线审查顺序",
    "scrub_review_providers_key_present": "已配置在线审查（只读）",
    "side_paint_auto_page": "长文自动分页",
    "side_paint_enabled": "帮助图侧立绘",
    "side_paint_filename": "立绘文件名",
    "side_paint_scale": "立绘缩放倍数",
    "sing_enable": "启用唱歌点歌",
    "sing_endpoint": "合成任务路径",
    "sing_length": "默认合成时长（秒）",
    "sing_speakers": "命令 → 音色",
    "smtp_password": "SMTP 密码",
    "smtp_port": "SMTP 端口",
    "smtp_server": "SMTP 服务器",
    "smtp_user": "SMTP 发信账号",
    "speak_continuously_max_len": "连说最多句数",
    "speak_continuously_probability": "连说概率",
    "speak_poke_probability": "发言戳一戳概率",
    "speak_threshold": "主动发言阈值",
    "split_probability": "拆句发送概率",
    "spy_default_blanks": "默认白板人数",
    "spy_default_undercovers": "默认卧底人数",
    "spy_email_fallback": "私聊失败改发邮箱",
    "spy_max_players": "房间人数上限",
    "spy_min_players": "最少开局人数",
    "spy_room_cleanup_sec": "空房清理等待（秒）",
    "spy_show_role_default": "私聊附带身份",
    "spy_auto_vote_when_all_spoken": "全员述词后自动投票",
    "spy_speak_max_len": "述词复盘单条字数上限",
    "spy_word_avoid_recent": "同群词对去重局数",
    "topics_importance": "关键词命中加成",
    "topics_size": "上下文关键词条数",
    "tts_enable": "启用语音合成",
    "tts_endpoint": "TTS 接口路径",
    "tts_route": "语音通路",
    "tts_timeout_sec": "TTS 提交超时（秒）",
    "tts_max_chars": "单次最大字数",
    "api_token": "API Bearer Token",
}


def webui_field_label(field_name: str) -> str:
    return FIELD_LABELS.get(field_name, "")
