"""面向用户的固定回复。"""

LLM_CHAT_VAGUE_REPLY = "嗯？方才没听清博士说什么，再说一次可好？"
LLM_CHAT_FAILED_REPLY = "我习惯了站着不动思考。有时候啊，也会被大家突然戳一戳，看看睡着了没有。"
LLM_CHAT_CLEAR_OK = "博士，你说过什么吗？"
LLM_CHAT_UNLOAD_OK = "那我先去歇会儿，博士想聊再叫我。"
LLM_CHAT_MODEL_CURRENT = "我现在用的是 {}。"
LLM_CHAT_MODEL_OK = "好，我换成 {} 了。"

OLLAMA_VAGUE_REPLY = LLM_CHAT_VAGUE_REPLY
OLLAMA_FAILED_REPLY = LLM_CHAT_FAILED_REPLY
OLLAMA_CLEAR_OK = LLM_CHAT_CLEAR_OK
OLLAMA_UNLOAD_OK = LLM_CHAT_UNLOAD_OK
OLLAMA_MODEL_CURRENT = LLM_CHAT_MODEL_CURRENT
OLLAMA_MODEL_OK = LLM_CHAT_MODEL_OK
