"""Console / ops-facing LLM entrypoints (WebUI, model admin, memory graph).

Prefer this facade over deep imports of ``providers_store``, ``webui_config``,
``model_admin``, or ``memory.graph`` from console API modules.
"""

from pallas.product.llm.ai_health_parse import (
    image_health_circuit,
    llm_health_from_provider_probe,
    llm_runtime_detail_from_provider_probe,
    parse_media_tasks,
    tts_health_summary,
)
from pallas.product.llm.behavior import BehaviorPattern, BehaviorScene
from pallas.product.llm.behavior_store import ensure_default_behavior_patterns
from pallas.product.llm.kernel.observability import (
    build_conversation_kernel_status,
    list_recent_conversation_traces,
)
from pallas.product.llm.knowledge.registry import (
    build_knowledge_source_detail_ui,
    list_active_knowledge_sources,
    probe_knowledge_source_retrieve,
)
from pallas.product.llm.media_assets import (
    delete_media_assets,
    fetch_media_assets_download_active,
    fetch_media_assets_download_job,
    fetch_media_assets_status,
    start_media_assets_download,
)
from pallas.product.llm.media_models import (
    fetch_sing_backends,
    fetch_sing_defaults,
    fetch_sing_speakers,
    fetch_tts_defaults,
    fetch_tts_translator,
    fetch_tts_voices,
    put_sing_defaults,
    put_tts_defaults,
    put_tts_translator,
)
from pallas.product.llm.memory.graph.extract import extract_from_episodes, extract_from_text
from pallas.product.llm.memory.graph.hiergraph import get_hiergraph_status, rebuild_hiergraph
from pallas.product.llm.memory.graph.import_export import export_scope_graph, import_scope_graph
from pallas.product.llm.memory.graph.service import (
    build_graph_payload,
    build_graph_stats,
    list_episodes,
    materialize_keyword_entities,
    materialize_relationship_notes,
    search_memory_graph,
)
from pallas.product.llm.memory.graph.store import (
    clear_scope_graph,
    delete_entity,
    list_categories,
    list_edges,
    list_entities,
    list_scopes,
    list_trash,
    purge_category,
    purge_entity,
    restore_category,
    restore_edge,
    restore_entity,
    soft_delete_category,
    soft_delete_edge,
    upsert_category,
    upsert_edge,
    upsert_entity,
)
from pallas.product.llm.memory.mid_term import list_mid_term_summaries
from pallas.product.llm.memory.ops import (
    apply_memory_lifecycle,
    build_memory_stats,
    clear_memory_entries,
    delete_memory_preference,
    list_memory_entity_summaries_async,
    list_memory_preferences,
    preview_memory_retrieve,
    upsert_memory_preference,
)
from pallas.product.llm.memory.relationship_store import delete_relationship_note, list_relationship_notes
from pallas.product.llm.memory.store import delete_memory_entry, list_memory_entries, save_memory_entry
from pallas.product.llm.model_admin import (
    fetch_llm_task_stats,
    fetch_local_routing_config,
    fetch_model_admin_status,
    fetch_provider_models,
    fetch_providers_config,
    get_runtime_model,
    probe_provider,
    reload_runtime_model,
    save_local_routing_config,
    save_providers_config,
    set_runtime_num_gpu,
    switch_runtime_model,
    unload_runtime_model,
    upsert_provider_config,
)
from pallas.product.llm.ops_config import (
    get_llm_memory_ops_config,
    get_llm_session_ops_config,
    memory_ops_patch_dict,
    session_ops_patch_dict,
)
from pallas.product.llm.promotion_candidates import (
    list_promotion_candidates,
    resolve_promotion_candidate_with_writeback,
)
from pallas.product.llm.providers_store import (
    bot_providers_configured,
    clear_providers_store_cache,
    export_providers_for_api,
    find_provider,
    load_providers_document,
    provider_allows_native_vision,
    provider_capabilities,
    provider_model_effort,
    provider_needs_vision_text_fallback,
    provider_request_method,
    provider_supports_capability,
    provider_task_model,
    providers_store_path,
    resolve_endpoint_candidates_for_task,
    resolve_endpoint_for_task,
    resolve_provider_api_key,
    resolve_provider_api_keys,
    resolve_provider_base_url,
    upsert_provider_row,
)
from pallas.product.llm.repeater_feedback import (
    clear_feedback_entry_correction,
    delete_feedback_entry,
    group_feedback_bias_snapshot,
    list_group_feedback_entries,
    set_feedback_entry_correction,
    set_feedback_entry_eligibility,
)
from pallas.product.llm.runtime_debug import build_replay_payload, load_runtime_debug_bundle
from pallas.product.llm.session_ops import (
    build_llm_history_stats,
    clear_llm_history_session,
    compact_llm_history_session,
    inject_llm_history_message,
)
from pallas.product.llm.session_store import (
    get_llm_history_session_detail,
    list_llm_history_sessions,
    update_llm_behavior_annotation,
)
from pallas.product.llm.startup_probe import probe_ai_service_health, probe_llm_provider
from pallas.product.llm.submit_gate import assess_llm_kernel_submit_gate
from pallas.product.llm.task_routing import build_task_routing_preview
from pallas.product.llm.tools.overrides import save_tool_overrides, upsert_tool_override
from pallas.product.llm.tools.preview import preview_tool_intent
from pallas.product.llm.tools.registry import build_tools_catalog_ui
from pallas.product.llm.webui_config import get_llm_webui_config

__all__ = [
    "BehaviorPattern",
    "BehaviorScene",
    "apply_memory_lifecycle",
    "assess_llm_kernel_submit_gate",
    "bot_providers_configured",
    "build_conversation_kernel_status",
    "build_graph_payload",
    "build_graph_stats",
    "build_knowledge_source_detail_ui",
    "build_llm_history_stats",
    "build_memory_stats",
    "build_replay_payload",
    "build_task_routing_preview",
    "build_tools_catalog_ui",
    "clear_feedback_entry_correction",
    "clear_llm_history_session",
    "clear_memory_entries",
    "clear_providers_store_cache",
    "clear_scope_graph",
    "compact_llm_history_session",
    "delete_entity",
    "delete_feedback_entry",
    "delete_media_assets",
    "delete_memory_entry",
    "delete_memory_preference",
    "delete_relationship_note",
    "ensure_default_behavior_patterns",
    "export_providers_for_api",
    "export_scope_graph",
    "extract_from_episodes",
    "extract_from_text",
    "fetch_llm_task_stats",
    "fetch_local_routing_config",
    "fetch_media_assets_download_active",
    "fetch_media_assets_download_job",
    "fetch_media_assets_status",
    "fetch_model_admin_status",
    "fetch_provider_models",
    "fetch_providers_config",
    "fetch_sing_backends",
    "fetch_sing_defaults",
    "fetch_sing_speakers",
    "fetch_tts_defaults",
    "fetch_tts_translator",
    "fetch_tts_voices",
    "find_provider",
    "get_hiergraph_status",
    "get_llm_history_session_detail",
    "get_llm_memory_ops_config",
    "get_llm_session_ops_config",
    "get_llm_webui_config",
    "get_runtime_model",
    "group_feedback_bias_snapshot",
    "image_health_circuit",
    "import_scope_graph",
    "inject_llm_history_message",
    "list_active_knowledge_sources",
    "list_categories",
    "list_edges",
    "list_entities",
    "list_episodes",
    "list_group_feedback_entries",
    "list_llm_history_sessions",
    "list_memory_entries",
    "list_memory_entity_summaries_async",
    "list_memory_preferences",
    "list_mid_term_summaries",
    "list_promotion_candidates",
    "list_recent_conversation_traces",
    "list_relationship_notes",
    "list_scopes",
    "list_trash",
    "load_providers_document",
    "load_runtime_debug_bundle",
    "llm_health_from_provider_probe",
    "llm_runtime_detail_from_provider_probe",
    "materialize_keyword_entities",
    "materialize_relationship_notes",
    "memory_ops_patch_dict",
    "parse_media_tasks",
    "preview_memory_retrieve",
    "preview_tool_intent",
    "probe_ai_service_health",
    "probe_knowledge_source_retrieve",
    "probe_llm_provider",
    "probe_provider",
    "provider_allows_native_vision",
    "provider_capabilities",
    "provider_model_effort",
    "provider_needs_vision_text_fallback",
    "provider_request_method",
    "provider_supports_capability",
    "provider_task_model",
    "providers_store_path",
    "purge_category",
    "purge_entity",
    "put_sing_defaults",
    "put_tts_defaults",
    "put_tts_translator",
    "rebuild_hiergraph",
    "reload_runtime_model",
    "resolve_endpoint_candidates_for_task",
    "resolve_endpoint_for_task",
    "resolve_promotion_candidate_with_writeback",
    "resolve_provider_api_key",
    "resolve_provider_api_keys",
    "resolve_provider_base_url",
    "restore_category",
    "restore_edge",
    "restore_entity",
    "save_local_routing_config",
    "save_memory_entry",
    "save_providers_config",
    "save_tool_overrides",
    "search_memory_graph",
    "session_ops_patch_dict",
    "set_feedback_entry_correction",
    "set_feedback_entry_eligibility",
    "set_runtime_num_gpu",
    "soft_delete_category",
    "soft_delete_edge",
    "start_media_assets_download",
    "switch_runtime_model",
    "tts_health_summary",
    "unload_runtime_model",
    "update_llm_behavior_annotation",
    "upsert_category",
    "upsert_edge",
    "upsert_entity",
    "upsert_memory_preference",
    "upsert_provider_config",
    "upsert_provider_row",
    "upsert_tool_override",
]
